version: '3.8'

services:
  # FastAPI backend
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_project_flow
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
    
  # PostgreSQL database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ai_project_flow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    
  # Celery worker for background tasks
  celery:
    build: .
    command: celery -A app.services.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_project_flow
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts

volumes:
  postgres_data:
